apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel-demo

resources:
- namespace.yaml
- deployment.yml
- service.yaml
- ingress.yaml

commonLabels:
  app: gateway-api
  app-purpose: otel-demo
